/**:
  ros__parameters:
    control_period: 0.1
    linear_gain: 0.65
    angular_gain: 1.4
    min_linear_speed: 0.15
    max_linear_speed: 0.75
    max_angular_speed: 0.55
    distance_tolerance: 0.15
    odom_timeout: 0.5
